version: '2'

services:

  issue_feedback_sanic:
    restart: always
    build: ../
    ports:
      - 8923:8000
    volumes:
      - ../src:/opt/app
      - ../docs:/opt/docs
    environment:
      STAGE: docker_compose
    command: sleep 999999999

  cassandra:
    restart: always
    image: cassandra:3.11
    ports:
      - 9042:9042

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  create_profile_projector:
    restart: always
    build: ../
    volumes:
      - ../src:/opt/app
    environment:
      STAGE: docker_compose
    command: python projector/create_profile.py
