name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kevinanew/python-driver:1.3.8
    steps:
    - uses: actions/checkout@v1

    - run: pip install -q -r src/requirements.txt --no-cache-dir

    - name: Run lint
      run: |
        yapf -dr src -e 'src/issue/*' | (! grep '.')
        pylava src --skip '*/tests/*,*/configs/*,*/aiocqlengine/models.py'
        isort -rc src --check-only --diff
